Intializing the diferent types of arrays

In [1]:
import numpy as np

In [3]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [4]:
b=np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
c=np.full((2,3),5)
print(c)

[[5 5 5]
 [5 5 5]]


In [6]:
d=np.random.rand(2,3)
print(d)

[[0.21192097 0.78399936 0.36863112]
 [0.89089279 0.0965388  0.42388083]]


In [17]:
e=np.random.randint(1,11,(2,3))
print(e)

[[ 8  2  1]
 [10  6 10]]


In [24]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
# print(z)
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
