Accessing the values from dimensional array rows or coloumns 

In [1]:
import numpy as np

In [2]:
a=np.array([[1, 2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
a.shape

(2, 7)

In [5]:
# get the specific element
print(a[1,5])


13


In [6]:
# get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [8]:
# get the clomn
print(a)
print(a[:,2])



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[ 3 10]


In [17]:
# start end and step
print(a[0,1:-1:2])

[2 4 6]


In [18]:
# to change the element in the array
a[1,3]=100
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10 100  12  13  14]]


In [19]:
a[:,2]=0
print(a)

[[  1   2   0   4   5   6   7]
 [  8   9   0 100  12  13  14]]


In [20]:
a[:,2]=[1,2]
print(a)

[[  1   2   1   4   5   6   7]
 [  8   9   2 100  12  13  14]]


3d array exmple

In [22]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print(b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [23]:
b.ndim

3

In [24]:
# getting the specific element in the 3D array
print(b[0,1,1])
print(b[1,0,0])

4
5


In [25]:
print(b[:,1,:])

[[3 4]
 [7 8]]
