In [1]:
import numpy as np

In [9]:
a=np.array([1,2,3,4,5,6],dtype=np.int8) #1D array
print(a)

[1 2 3 4 5 6]


In [ ]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) #2D array
print(b) 

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# get the dimensions of the arrays
print(a.ndim) #1D array
print(b.ndim) #2D array

1
2


In [6]:
# get shape of the arrays
print(a.shape) #1D array has shape (6,)
print(b.shape) #2D array has shape (2, 3)

(6,)
(2, 3)


In [10]:
# get data type of the arrays
print(a.dtype) #1D array has data type int64
print(b.dtype) #2D array has data type float64

int8
float64


In [11]:
# get item size of the array
print(a.itemsize) #1D array has item size 1 byte
print(b.itemsize) #2D array has item size 8 bytes

1
8


In [13]:
# get total size of the array
print(a.nbytes) #1D array has total size 6
print(b.nbytes) #2D array has total size 48

6
48
